const ADMIN_SITEURL = process.env.ADMIN_SITEURL;
const FRONTEND_SITEURL = process.env.FRONTEND_SITEURL;
const OTPLESS_CLIENT_ID = process.env.OTPLESS_CLIENT_ID;
const OTPLESS_CLIENT_SECRET = process.env.OTPLESS_CLIENT_SECRET;
const OTPLESS_APP_ID = process.env.OTPLESS_APP_ID;
module.exports = {
  ADMIN_SITEURL,
  FRONTEND_SITEURL,
  OTPLESS_CLIENT_ID,
  OTPLESS_CLIENT_SECRET,
  OTPLESS_APP_ID,
};
